### ISSUE TITLE
Usage in AOT compiled Angular applications

### ISSUE THREAD

**Issue by cmckni3** [LogRocket/logrocket-ngrx#1]
Not sure where to document this but the configuration needs to change.

Since the `createMetaReducer` method is dynamic, it interferes with AOT compilation. The Angular compiler emits an error, `Function calls are not supported in decorators`, when a module calls a method that isn't wrapped in a `NgModule`.

Dependency injection to the rescue!

My implementation to solve this issue is to dynamically initialize `logrocket-ngrx`.

```typescript
// logrocket.reducer.ts
import * as LogRocket from 'logrocket';
import createNgrxMiddleware from 'logrocket-ngrx';

// opts is the same object you would normally pass to LogRocket.reduxMiddleware()
export const logrocketMiddleware = createNgrxMiddleware(LogRocket, {});
```

```typescript
// app.module.ts
import { META_REDUCERS, MetaReducer, StoreModule } from '@ngrx/store';
import { StoreDevtoolsModule } from '@ngrx/store-devtools';
import { logrocketMiddleware, metaReducers, reducers, State } from './store';

export function getMetaReducers(): MetaReducer<State>[] {
    return metaReducers.concat([logrocketMiddleware]);
}

@NgModule({
  imports: [
    StoreModule.forRoot(reducers)
  ],
  providers: [
    {
      provide: META_REDUCERS,
      useFactory: getMetaReducers,
    }
  ]
})
export class AppModule {}
```

Reference: https://github.com/ngrx/platform/blob/master/docs/store/api.md#injecting-meta-reducers

**Comment by eranimo** [comment]
@cmckni3 Thank you! I wasn't familiar with Angular's AOT feature. I will update our docs to include these steps.
