### ISSUE TITLE
"Mixing multi and non multi provider is not possible for token InjectionToken__ngrx_store_Meta_Reducers"

### ISSUE THREAD

**Issue by virtuoushub** [LogRocket/logrocket-ngrx#4]
I tried using the documented example in #1 and ran into the following issue:

```
Mixing multi and non multi provider is not possible for token InjectionToken__ngrx_store_Meta_Reducers
```

I looked into it a bit and am not sure what is causing the above error.

**Comment by rlucioni** [comment]
Hi @virtuoushub, sorry it's taken so long to get back to you here. I know you've likely either moved on and/or figured this out, but for the record, I've updated our [docs](https://docs.logrocket.com/docs/ngrx-middleware) to reflect both the example in #1 and a fix that should avoid the issue you encountered. Happy holidays!
